/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package EmailClientApp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class ComposeArea extends javax.swing.JFrame {

    
    Connection con;
    Statement stmt;
    PreparedStatement stat;
    /**
     * Creates new form ComposeArea
     */
    public ComposeArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        ToName = new javax.swing.JLabel();
        ToField = new javax.swing.JTextField();
        SubjectName = new javax.swing.JLabel();
        SubjectField = new javax.swing.JTextField();
        SendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lbFrom = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ToName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ToName.setText("TO");
        ToName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ToField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        SubjectName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubjectName.setText("SUBJECT");

        SubjectField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SubjectField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        SendButton.setBackground(new java.awt.Color(255, 255, 255));
        SendButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SendButton.setText("SEND");
        SendButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        MessageField.setColumns(20);
        MessageField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        MessageField.setRows(5);
        jScrollPane1.setViewportView(MessageField);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FROM");

        lbFrom.setText("jLabel2");

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubjectName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubjectField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ToName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ToField)
                                    .addComponent(lbFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbFrom))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubjectName)
                    .addComponent(SubjectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        // TODO add your handling code here:
 
            if(!ToField.getText().equals("") && !SubjectField.getText().equals("") && !MessageField.getText().equals(""))
            {
                try 
                {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-BL4ATQN; databaseName=EmailClient;user=sa;password=123456");
                    stmt = con.createStatement();  
                    
                    stat = con.prepareStatement("INSERT INTO Store VALUES(?,?,?,?)");
                   
                    String sender = lbFrom.getText();
                    String receiver = ToField.getText();
                    String subject = SubjectField.getText();
                    String body = MessageField.getText();

                    stat.setString(1, sender);
                    stat.setString(2, receiver);
                    stat.setString(3, subject);
                    stat.setString(4, body);
                  
                    stat.executeUpdate();

                    lbFrom.setText("");
                    ToField.setText("");
                    SubjectField.setText("");
                    MessageField.setText("");
                    
                    JOptionPane.showMessageDialog(null,"Message successfully sent");
                }
                catch(Exception ex){
                     JOptionPane.showMessageDialog(null, ex.getMessage());
                }          
            }
            else{
                 JOptionPane.showMessageDialog(null, "Empty fields are not allowed");
            }
        
        
    }//GEN-LAST:event_SendButtonActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
         new Inbox().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCloseActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MessageField;
    private javax.swing.JButton SendButton;
    private javax.swing.JTextField SubjectField;
    private javax.swing.JLabel SubjectName;
    private javax.swing.JTextField ToField;
    private javax.swing.JLabel ToName;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbFrom;
    // End of variables declaration//GEN-END:variables
}
