package EmailClientApp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Inbox extends javax.swing.JFrame {

    public String CurrentUser;
    
    Connection con;
    Statement stmt;
    PreparedStatement stat;
    /**
     * Creates new form Inbox
     */
    public Inbox() {
        initComponents();
        //DoBind();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncomp = new javax.swing.JButton();
        lbBox = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mailsTable = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnLoadMails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btncomp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btncomp.setText("COMPOSE");
        btncomp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncompActionPerformed(evt);
            }
        });

        lbBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbBox.setText("INBOX");

        mailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sender", "Subject", "Message"
            }
        ));
        jScrollPane1.setViewportView(mailsTable);

        btnClose.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnLoadMails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLoadMails.setText("Load Mails");
        btnLoadMails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadMailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoadMails)
                        .addGap(158, 158, 158)
                        .addComponent(btncomp, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncomp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose)
                    .addComponent(btnLoadMails))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompActionPerformed
        this.setVisible(false);
        ComposeArea myComposeArea = new ComposeArea();
        myComposeArea.lbFrom.setText(this.CurrentUser);
        myComposeArea.setVisible(true);                 
    }//GEN-LAST:event_btncompActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            if(!this.CurrentUser.equals("")){
            try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-BL4ATQN; databaseName=EmailClient;user=sa;password=123456");
                stmt = con.createStatement();  
                stat = con.prepareStatement("SELECT Sender, Receiver, Subject, Message FROM Store WHERE Receiver=?");

                stat.setString(1, this.CurrentUser);
                ResultSet rs= stat.executeQuery();
                mailsTable = new JTable(buildTableModel(rs));
            }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void DoBind(){
       
           if(!this.CurrentUser.equals("")){
            try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-BL4ATQN; databaseName=EmailClient;user=sa;password=123456");
                stmt = con.createStatement();  
                stat = con.prepareStatement("SELECT Sender, Receiver, Subject, Message FROM Store WHERE Receiver=?");
                
                stat.setString(1, this.CurrentUser);
                ResultSet rs= stat.executeQuery();
                mailsTable = new JTable(buildTableModel(rs));
                
                JOptionPane.showMessageDialog(null, "I'm here as " + this.CurrentUser);
            }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }
    
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
                 new frmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLoadMailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadMailsActionPerformed
        // TODO add your handling code here:
        try
        {
            //open connection
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-BL4ATQN; databaseName=EmailClient;user=sa;password=123456");
            
            Statement st = con.createStatement();
            String sql = "select Sender, Receiver, Subject, Message FROM Store WHERE Receiver=?";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next())
            {
                String Sender = rs.getString("Sender");
                String Subject = rs.getString("Subject");
                String Message = rs.getString("Message");
                
                //string array for storing data into the jtable
                String tbData[ ] = {Sender, Subject, Message};
                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                
                //add string array data into jtable
                tblModel.addRow(tbData);
            }
            
          con.close();
        } 
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        DoBind();
    }//GEN-LAST:event_btnLoadMailsActionPerformed

  private DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLoadMails;
    private javax.swing.JButton btncomp;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbBox;
    private javax.swing.JTable mailsTable;
    // End of variables declaration//GEN-END:variables
}
